"""
Django settings for pspdfkit_example project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import environ
import git
import os

from django.urls import reverse_lazy

root = environ.Path(__file__) - 2
env = environ.Env(DEBUG=(bool, False),)  # set default values and casting

repo = git.Repo(search_parent_directories=True)
GIT_SHA = repo.head.object.hexsha

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rfgl0%40b)=qnb0!i^5ls*@w89&e#70@lqp33@)%n2s-62e752'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'pipeline',

    # Local
    'pspdfkit_example.documents.apps.DocumentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pspdfkit_example.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            root.path('templates/'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pspdfkit_example.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

public_root = root.path('public/')

MEDIA_ROOT = public_root('media')
MEDIA_URL = '/media/'
STATIC_ROOT = public_root('static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    str(root.path('static/')),
]
STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
)
PIPELINE = {
    'STYLESHEETS': {
        'application': {
            'source_filenames': (
              'css/document.css',
              'css/login.css',
              'css/navbar.css',
              'css/scaffolding.css',
              'css/thumbnails.css',
            ),
            'output_filename': 'css/application-{}.css'.format(GIT_SHA),
        },
    },
}

LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('documents_list')
LOGOUT_REDIRECT_URL = reverse_lazy('login')


# PSPDFKit settings
PSPDFKIT_PRIVATE_KEY = """\
-----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEAvhnVp2kTOTeILLgTrVHtZTS5/EiJ0jJXzs+f5BtG6HscHO33
csm/5rfdBg1l+E1SnQeelP/8KCRKiECw69nnyGra+6XwByVVSAH/zIBBRGdKH/Eg
sz0/Zd0w94jvc9FYj0j2oYKjAHjera9Lac4PoIa/RW28Uo2gHjjOtFezSA77+Bfw
xHItfTeTVjrGA+5/rogc6CJ9FOcIhT/xA9i+J1obZvDeQwaPj7EOvMpqiJU2X7Xd
MZdnOFTIuckRaTCjof2ORG9mQ0s9eYEvd7PPrwtwbtmZ9K02LOXRzSoP7MbHW9/a
06yFZL8o/tYSXnPigKTd1GUSRB4mV4sc1chM9TMQBplS/yNKoogrjI27aqqMqIpJ
cFuPYOIgct7u2EaCoN4iMqAl0o7lGS9ab4eV3kBh2yiaP7+aJIS4/IdvZuWdDt1T
XSHjIkbDrNbwBj7W0sz3CxJXhQPYki4XC/5hCIqh1XDlkDTKjJf7hLBC+VGykndT
rNJnpRrEjo5cmF/XPB5UxGQGV7Cmh1ejKE+cwXIoC/fBp25b854FhlAVcPth6RJ5
0d03eur/J5T05kd9nrqM2dw6PUQzp8CA9QciDT+dKEUh0UOM8HRen9JwYs4vPEU2
Coh2oKkSO5uuR87S0GcaYANmBM/sNynYMQHdIr0riZaONoCGKlkO1NwaWSsCAwEA
AQKCAgBQKDCQwJuceq/uu0eAw5ToIc1ydVu3yAaCa8Wtt1q02IRIJoc6XZuPO2P1
E101z9TP5dCWX0IB4xuSTETNjjpPpc7kYVnOiY1mKYGkx0e+AhedVF1HdsHuv8/P
8GuXWGSRNmDYRW9Z2Z17evi/imXIeEjai6Tm4lTrqWRvYrNz5O2V9PJOwx4vOGnl
6C5qpfwsqbQWpcQ8Nha/qPCFgLTdfv8i7tmpRXDvU+c079zv7orY3KSCLqcVd5qT
zBaNVjcJLRL6BEcIhQdM3o4XWThvRNGJzDNAmnDHibhnXB8O5dpWARQSQSKWEozE
t5tTPGX7fIkU7/E9y8C7FSt5cVYRK/izBvF2W+N4F652bWLr+jj6iiLRJh19JLha
7+sdoLqWb3jr5TUioi1Tv/PnOcYRLEtrNxPsLk41zPKdxE+m3V9Spga939Qy+PYq
y5bv+mG9c1qQyCoyhdgmGsKC8dF7xLqftnnBavsAEcxi6AVWmK0Q9BWN6K0fKv0L
HtMNe+WFIuc2FagGCZJtifOmncgzZdeKc6SmqhfYs3Ss3J5BB0NaXXWbO5mkCxBs
CbYjT/LIwzQ0DFEZUQxoYvnhrB5/nW6QykadqU2RwfAb4IXh+oy5SdVAJo7UQJcu
EaVcrA3gq94hLjPqEhJEZEH+PTUvADGj3vOPbjmyWn3yMHY7wQKCAQEA4f+pz42Y
6c9hk1+u24Ox7O0VQDIoxyKMHk7ouNYsS5nTvJAj7FpeBOaR+OZ1RoKj0SiPe23X
A3F/pEgIJA+uVLSEi8O+mOC8xUaKORA6K152KkH5yDLlH2ZHY/gXXyfht9L+59D2
js4oTLxn/j701VhglDJ2bf2yD8um9iuGGUUd5fXbh+GoTHuA9O1nsGnDhocSLQ8v
zA6IDONlxxJSsvBqrvAQzcftphP0G2ZuGYAXsz8cW4jkHkzR0jzrFIaUGH6xwe1M
m9C5gqvXSQYpGNEgINOehbXZlTIPbqS3kxUh0J9gWfUhjpRauBe0xHa7pKcn5O+R
+o2/eKbuqSLgMQKCAQEA11Y4z2+j33S7aj1UcWBEPsXBGT0jhA8ftVWXVpCbauiW
MgK//p6QSBwBudGuRjbBiVx3UtbkJbCoCMXJiwdstA3WNwQkZNxZ7wPkEZoZZjfn
o+lVX3WoxFAXEdrxPzBtyIo040w40JPieuVkumNWfXeVY9HgRb2as2hP2ir9yyWq
KFKGGSLai+f2UYFLcCr1V3PWzNYOezQthgD6TNd9BUaynIe6aoeC/4vFrWCfN5Y/
EPdevwdNdKEaFQFQWowY+aGesRXynnp3wmEdNBPheX9ZuUUJbPIloYIZrWwlvYrV
rx16iSx67L3fFsa+Pl5qTo6bwTm3uF/VualHIh70GwKCAQEAnCeOSrYY+Tzsu+q6
JD0L3Jw4OcIuwOGTFYIKdWSu+JHSZpDl8XLDUfmK1QNP9ydfT68J7QwJK/zpaDbJ
QTmAiFCu4O+gq3tlk53Y9fLLbpn3Zd1uXLEl9ZszKtUKORqScPSeYsjVA/lYiSUJ
afhQLXXCTcPMZtWLijR6KdAK+TzzmqhVRr9aDXastQ+wvIlnq3V6zp2WthU4Vkdt
VK7Ja5CI9lU0FyvUfhN9cM1Gt+H0/kpWKr0cef80X2LuP6F5hK9N3aQ8cdE3zR01
ROS30sj0vRnbh6IONHOBjD7OBRft5HurFJ020ZCaWmcu5SzxHKTPAPWz1P7KVPBr
KXzKkQKCAQAUDlvMNkG1FlI+Wuf6h1TT4+dQSnl8W0xAv3ARB/bxxif3EHqBZJNb
pAAlJnps37y25n3WoV0uhX2hE4rqAA8H1iIVjbU2D6/wqxQa75deBeb1RU5GTdci
MbN0XkgJ8qDHBNhYM0k3ZA68E5GGKqprlS+81FdnJ3m5LAYD8+0fdqqahtUmkjB4
x2oRvVEhaV7gflGLUoSWxQ1YZc7qSUfDrgoEuj+KnIR++K24sD8kFkJZejDA6hU0
v6yGOFEbneDVn1AAfmLSj+WHnTPzHcbqYgohT2TJWORYXp21oVUCimPMo5o+HH52
fljA7lHZzUFpf67SGGYcLhDh8fpGG0vxAoIBABa/qs+qpm1t/gVYu6foFPmgt7Bl
Zq+twNBhtx1HUd1ksmaAF2AYZRICtP6JouGnwrQpU+vY1CGsBSMIhBhpMuYV6M3o
CTB6fi1UGbtUr0KZgc2dJe05FCt4G+3IYDuODhoBHqv8yU3mzI6GvV0rA+IIFq99
vNPNnl5g0vMM332C+FgH6nQKrt0WljSEZqIVAQI7A7LSEHCs2RKSl66k/Kn9eC6Z
aavyscJAMdXk/UQ7qZIxSzP1vR+6QML2+9hI+3iqCW7svFJ1E557jf5LKqWvOg/i
Cg7ISgPOnGP6VgPLMTdYEv1pQqI2vcDX3uKSx9qaa8A+BbYAkc4egt1COoE=
-----END RSA PRIVATE KEY-----
"""
PSPDFKIT_API_AUTH_TOKEN = env('API_AUTH_TOKEN')
PSPDFKIT_SERVER_HOST = env('PSPDFKIT_SERVER_INTERNAL_URL')  # API
PSPDFKIT_EXTERNAL_SERVER = env('PSPDFKIT_SERVER_EXTERNAL_URL')  # JS file

EXAMPLE_FILE_PATH = str(root.path('static/example.pdf'))

# Auth
AUTHENTICATION_BACKENDS = (
    'pspdfkit_example.backend.SimpleAuthBackend',
)
